name: fluttercamera
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  camera: ^0.9.4+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.3.8
  get_storage: ^2.0.3
  image: ^3.0.8
  image_gallery_saver: ^1.7.0
  image_picker: ^0.8.4+2
  path_provider: ^2.0.5
  photo_view: ^0.12.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
